openapi: 3.0.0
info:
  title: Ask Endpoint
  version: 1.0.0
paths:
  /ask:
    post:
      summary: Query the RAG agent with a general question.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The question to ask the RAG agent.
              example:
                query: "What are the main components of a humanoid robot?"
      responses:
        '200':
          description: Successful response from the RAG agent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer provided by the RAG agent based on the book content.
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                          description: The source file of the retrieved chunk.
                        heading:
                          type: string
                          description: The heading of the retrieved chunk.
                        text_snippet:
                          type: string
                          description: A snippet of the text from the retrieved chunk.
        '400':
          description: Invalid request or missing query.
        '500':
          description: Internal server error.